import os
Import("env")
Import("bin_dir")
Import("guess_os")

# build
if guess_os == "win32":
   sundownFiles = [
      "src/autolink.c",
      "src/buffer.c",
      "src/markdown.cpp",
      "src/stack.c",
      "src/renderer.c",
      "src/table.cpp",
      "src/main.cpp",
      "src/win/getopt.c"
      ]
else:
   sundownFiles = [
      "src/autolink.c",
      "src/buffer.c",
      "src/markdown.cpp",
      "src/stack.c",
      "src/renderer.c",
      "src/table.cpp",
      "src/main.cpp"
      ]
      
#md2TroffTool convertor executable
md2TroffTool = env.Program("md2TroffTool", sundownFiles,
                           _LIBDEPS='$_LIBDEPS_OBJS' )

env.Install( bin_dir, md2TroffTool )

