alter table warehouse drop constraint pk_warehouse;
alter table district drop constraint pk_district;
alter table item drop constraint pk_item;
alter table new_order drop constraint pk_new_order;
alter table oorder drop constraint pk_oorder;
alter table customer drop constraint pk_customer;
alter table order_line drop constraint pk_order_line;
alter table stock drop constraint pk_stock;
drop index k_warehouse ;
drop index k_district ;
drop index k_item ;
drop index ndx_oorder_carrier ;
drop index k_new_order ;
drop index ndx_customer_name ;
drop index k_oorder ;
drop index k_customer ;
drop index k_order_line ;
drop index k_stock ;
commit;
