#ifndef FILELIST_GENERATOR_HPP
#define FILELIST_GENERATOR_HPP

#include "../generateInterface.hpp"

/* =============== statement =============== */
#define SPIDER_MONKEY_CODE_STATEMENT "// this file is automatically generated. DO NOT MODIFY IT!"

#define SPIDER_MONKEY_SOURCE_FILE_LIST \
   "error", \
   "sdb",   \
   "help",  \
   "sdbSP", \

#define ENGINE_SPT_PATH       ENGINE_PATH"spt/"
#define JS_IN_CPP_FILE_PATH   ENGINE_SPT_PATH"js_in_cpp.hpp"

class codeGenerator : public generateBase
{
DECLARE_GENERATOR_AUTO_REGISTER() ;

public:
   codeGenerator() ;
   ~codeGenerator() ;
   int init() ;
   bool hasNext() ;
   int outputFile( int id, fileOutStream &fout,
                   string &outputPath ) ;
   const char* name() { return "js code" ; }

private:
   bool _isFinish ;
} ;

#endif
