
#ifndef OSSVER_AUTOGEN_H_
#define OSSVER_AUTOGEN_H_

#define SDB_ENGINE_OSSVER_FILE "ossVer_Autogen.h"
#define SDB_ENGINE_INCLUDE_AUTOGEN_RELATIVE_PATH "../../SequoiaDB/engine/include/"
#define SDB_ENGINE_OSSVER_FILE_RELATIVE_PATH SDB_ENGINE_INCLUDE_AUTOGEN_RELATIVE_PATH SDB_ENGINE_OSSVER_FILE

#define SDB_ENGINE_RELEASE_CURRENT 34790
#define SDB_ENGINE_BUILD_FORMAT "%04d-%02d-%02d-%02d.%02d.%02d"
#define SDB_ENGINE_BUILD_CURRENT "0000-00-00-00.00.00"

#endif /* OSSVER_AUTOGEN_H_ */
